### ISSUE TITLE
Warnings while making the sample files

### ISSUE THREAD

**Issue by rinka-meltiron** [ahgamut/debug-cosmo-example#1]
Hi,
I have the following issues when building the sample files.  Please will you fix these:
1. I generally use -Wall to flush out all warnings.  Please will you add this to your Makefile.
2. (Not sure if you do) Don't you need the -ggdb flag?  You can ignore this if it is not necessary - I suspect you don't need it but thought I'd bring it up anyway.
3. Warning while compiling:
```
cc -g3 -O2 -static -nostdlib -nostdinc -fno-pie -no-pie -mno-red-zone -fno-omit-frame-pointer -pg -mnop-mcount -mno-tls-direct-seg-refs -gdwarf-4  -I./header_stubs -include ..//cosmopolitan.h -o hex16.com.dbg hex16.c -fuse-ld=bfd -Wl,-T,..//ape.lds -Wl,--gc-sections ..//crt.o ..//ape-no-modify-self.o ..//cosmopolitan.a
In file included from <command-line>:31:
./..//cosmopolitan.h:28099: warning: "IFNAMSIZ" redefined
28099 | #define IFNAMSIZ    IF_NAMESIZE
      | 
./..//cosmopolitan.h:27996: note: this is the location of the previous definition
27996 | #define IFNAMSIZ 16
      | 
```

4. Warning while linking:
```
/usr/bin/ld.bfd: warning: .note.gnu.build-id section discarded, --build-id ignored
objcopy -S -O binary hex16-ubsan.com.dbg hex16-ubsan.com
```

**Comment by ahgamut** [comment]
Hi @rinka-meltiron, 

1. `-Wall` is a good idea, I will add that to the Makefile soon
2. We don't need the `-ggdb` because the binaries do not link to `gdb`. When the program crashes, Cosmopolitan Libc's crash handler basically calls `gdb` from the commandline via `execv` (see [here](https://github.com/jart/cosmopolitan/blob/master/libc/log/attachdebugger.c#L87)) with the necessary information from the binary
3. That warning is okay (@jart probably some `ifdef` isn't translating?)
4. the linker warning is also okay, it's just removing a build id hash that gcc wanted to add

**Comment by ahgamut** [comment]
updated Makefile with `-Wall`

**Comment by rinka-meltiron** [comment]
Hi @ahgamut , @jart 
Thanks for addressing these.  While a lot of people don't consider this a major issue, we abort the build on warnings (it has paid off for us many times).

For us to experiment with/use these libraries, we must eliminate all warnings.

TIA,
